spring.application.name=lindasso

spring.datasource.url=jdbc:postgresql://meu-postgres:5432/minhabd
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true